  server:
    port: 8080

  spring:
    datasource:
      username: admin
      password: admin
      url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: xin.shaonianyou.forum.entity

  #showSql
  logging:
    level:
      com:
        example:
          mapper : debug
